# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e0f4dfac0ebbaeedd831f58b2ff79968b33b81fda7570a3721a08db09e96c4dd77a9d69e7473dfba5ce4cab1eb3cccfbac68344c3588c9224a9fac470ab7b4a

test:
  secret_key_base: f5b25d1308a2a4e782e3725e3d9d5ffa6f3004cbaba6dff3fcb00de8e4d19efadd60a28c88b2ff075877bdcab186ec2135747e1335b0991cde8693c34542c30b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
